[options]
proxy_mode = True
# If you are using the websocket configuration in Nginx above, you must define workers.
# If workers = 0, Odoo does not spin up the port 8072 websocket service.
workers = 2